module.exports = [
    {
        id: 0,
        header: 'Terrarium background creation',
        image_header: require('../images/articles/finished.jpg'),
        image_first: require('../images/articles/2.jpg'),
        image_second: require('../images/articles/1.jpg'),
        image_third: require('../images/articles/final.jpg'),
        article_text_first: 'In this article I will lead you through terrarium creation from start to finish.',
        article_text_second: 'As a first thing you need to do is make something like spine of our background. I am making my "spine" from polystyrene as it is easy to carve shapes to create desired look. You can also use other material, but polystyrene works for me the best.',
        article_text_third: 'After you have created desired shape, you can start adding layers of tile adhesive. After applying atleast 3 layers, you can then apply last layer which will be color of your background. I am using yellow color as it makes interier of terrarium significantly brighter. After all that hard work make sure to secure background in terrarium with glue, so it doesnt fall when your chonky bearded dragon leaps from one platform to another.'
    },
    {
        id : 1,
        header: 'Work in progress',
        image_header: require('../images/articles/placeholder-image.png'),
        image_first: require('../images/placeholder-image.png'),
        image_second: require('../images/placeholder-image.png'),
        article_text_first: '------------- Work in progress -------------',    
        article_text_second: '------------- Work in progress -------------',   
        article_text_third: '------------- Work in progress -------------',  
    }, 
    {
        id : 2,
        header: 'Work in progress',
        image_header: require('../images/articles/placeholder-image.png'),
        image_first: require('../images/placeholder-image.png'),
        image_second: require('../images/placeholder-image.png'),
        article_text_first: '------------- Work in progress -------------',    
        article_text_second: '------------- Work in progress -------------',   
        article_text_third: '------------- Work in progress ------------- ',  
    }, 
    {
        id : 3,
        header: 'Work in progress',
        image_header: require('../images/articles/placeholder-image.png'),
        image_first: require('../images/placeholder-image.png'),
        image_second: require('../images/placeholder-image.png'),
        article_text_first: '------------- Work in progress -------------',    
        article_text_second: '------------- Work in progress -------------',   
        article_text_third: '------------- Work in progress -------------',  
    }, 
]